### ISSUE TITLE
License compatibility and contributing

### ISSUE THREAD

**Issue by divanvisagie** [Jupp56/skyrim_savegame#1]
Hi, I have forked your repo since I want to use your parser in a project of mine (my own attempts kind of blew up when I hit the plugins array.

Anyway I see that there is no license on this repo and my app would be MIT. Would you be interested in adding a license file here and also taking contributions? I see that there could be simple changes to make it compatible with Skyrim 2011 for instance.

**Comment by Jupp56** [comment]
Oh, the message went under in my inbox. Ill add a License right away. Note, this is not complete nor any stability guarantee given.

**Comment by Jupp56** [comment]
Resolved - Project is available under MIT

**Comment by Jupp56** [comment]
> Hi, I have forked your repo since I want to use your parser in a project of mine (my own attempts kind of blew up when I hit the plugins array.
> 
> Anyway I see that there is no license on this repo and my app would be MIT. Would you be interested in adding a license file here and also taking contributions? I see that there could be simple changes to make it compatible with Skyrim 2011 for instance.

PRs are welcome
